/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("/playermodel.gltf");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Body.geometry}
        material={materials.Material}
        scale={[1, 0.927, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Head.geometry}
        material={materials.Material}
        position={[0, 0.812, 0]}
        scale={0.626}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Hair.geometry}
        material={materials.Material}
        position={[0, 0.812, 0]}
        scale={0.626}
      />
    </group>
  );
}

useGLTF.preload("/playerModel.gltf");
